name: Build Docker Image

on:
  push:
    branches:
      - main


jobs:
  Build-and-push:
    name: Build and Push Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate SHA
        id: sha
        run: echo "::set-output name=sha::$(echo $GITHUB_SHA | cut -c1-7)"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: initial:${{ steps.sha.outputs.sha }}

      - uses: kitabisa/docker-slim-action@v1
        env:
          DSLIM_HTTP_PROBE: false
        with:
          target: initial:${{ steps.sha.outputs.sha }}
          tag: "alan01777/testeapi:v${{ steps.sha.outputs.sha }}"

      # Push to the registry
      - run: docker image push "teste-api" --all-tags

