name: Build Docker Image

on:
  push:
    branches:
      - main


jobs:
  Build-and-push:
    name: Build and Push Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate SHA
        id: sha
        run: echo "::set-output name=sha::$(echo $GITHUB_SHA | cut -c1-7)"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: alan01777/sistema-consultas-medicas:${{ steps.sha.outputs.sha }}

      - name: Get SlimToolKit
        shell: bash
        run: |
          curl -sL https://raw.githubusercontent.com/slimtoolkit/slim/master/scripts/install-slim.sh | sudo -E bash -

      - name: Run SlimToolKit
        shell: bash
        run: |
          slim build --target alan01777/sistema-consultas-medicas:${{ steps.sha.outputs.sha }} --tag alan01777/sistema-consultas-medicas:slim-${{ steps.sha.outputs.sha }} --include-path / --http-probe-off true

      # Push to the registry
      - name: Tag and Push
        run: |
          docker tag alan01777/sistema-consultas-medicas:${{ steps.sha.outputs.sha }} alan01777/sistema-consultas-medicas:latest
          docker tag alan01777/sistema-consultas-medicas:slim-${{ steps.sha.outputs.sha }} alan01777/sistema-consultas-medicas:slim-latest
          docker push alan01777/sistema-consultas-medicas --all-tags

