name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate Short SHA
        id: sha
        run: echo "short_sha=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: alan01777/sistema-consultas-medicas:${{ env.short_sha }}

      - name: Tag Latest
        run: docker tag alan01777/sistema-consultas-medicas:${{ env.short_sha }} alan01777/sistema-consultas-medicas:latest

      - name: Push Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            alan01777/sistema-consultas-medicas:${{ env.short_sha }}
            alan01777/sistema-consultas-medicas:latest

