name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate Short SHA
        id: sha
        run: echo "short_sha=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: alan01777/sistema-consultas-medicas:${{ env.short_sha }}

      - name: Slim Image
        uses: kitabisa/docker-slim-action@v1
        env:
          DSLIM_HTTP_PROBE: false
        with:
          target: alan01777/sistema-consultas-medicas:${{ env.short_sha }}
          tag: slim-${{ env.short_sha }}

      - name: Inspect Image Sizes
        run: |
          docker images alan01777/sistema-consultas-medicas:${{ env.short_sha }}
          docker images alan01777/sistema-consultas-medicas:slim-${{ env.short_sha }}

      - name: Push SHA image
        run: |

          docker push alan01777/sistema-consultas-medicas:${{ env.short_sha }}
          docker push alan01777/sistema-consultas-medicas:slim-${{ env.short_sha }}


      - name: Tag and Push Latest Image
        run: |
          docker tag alan01777/sistema-consultas-medicas:slim-${{ env.short_sha }} alan01777/sistema-consultas-medicas:slim-latest
          docker tag alan01777/sistema-consultas-medicas:${{ env.short_sha }} alan01777/sistema-consultas-medicas:latest
          docker push alan01777/sistema-consultas-medicas:slim-latest
          docker push alan01777/sistema-consultas-medicas:latest

