name: Build Docker Image

on:
  push:
    branches:
      - main


jobs:
  Build-and-push:
    name: Build and Push Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate SHA
        id: sha
        run: echo "::set-output name=sha::$(echo $GITHUB_SHA | cut -c1-7)"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: alan01777/laravelapi:start

      - uses: kitabisa/docker-slim-action@v1.1.1
        env:
          DSLIM_HTTP_PROBE: false
        with:
          target: alan01777/laravelapi:start
          tag: "${{ steps.sha.outputs.sha }}"

      # Push to the registry
      - name: Tag and Push
        run: |
          docker image push alan01777/laravelapi:${{ steps.sha.outputs.sha }}
          docker tag alan01777/laravelapi:${{ steps.sha.outputs.sha }} alan01777/laravelapi:latest
          docker image push alan01777/laravelapi:latest

