name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.31.1
        with:
          php-version: '8.3'
          extensions: pdo, pd_pgsql, zip
          tools: composer:v2, php-cs-fixer, phpunit

      - name: Install Dependencies
        run: composer install

      - name: Run Tests
        run: php artisan test
