# This YAML file defines a GitHub Actions workflow named "Run Tests" that runs tests for a Laravel API project.
name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.31.1
        with:
          php-version: '8.3'
          extensions: pdo, pdo_pgsql, zip
          tools: composer:v2, php-cs-fixer, phpunit

      - name: Install Dependencies
        run: composer install

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run Tests
        env:
          DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
          DB_URL: postgresql://postgres.xadtqkvxwpbuauxeoell:wow01777121518@aws-0-sa-east-1.pooler.supabase.com:6543/postgres
          DB_HOST: aws-0-sa-east-1.pooler.supabase.com
          DB_PORT: 6543
          DB_DATABASE: postgres
          DB_USERNAME: postgres.xadtqkvxwpbuauxeoell
          DB_PASSWORD: wow01777121518
        run: php artisan test